### ISSUE TITLE
Client: Improve initialization when not logged in

### ISSUE THREAD

**Issue by fcatae** [DXBrazil/dxconfig#2]
Error: ENOENT: no such file or directory, open 'C:\Users\fcatae\AppData\Local\DXConfig\configserver.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.readJson (C:\Users\fcatae\AppData\Roaming\npm\node_modules\dxconfig\lib\platform\files.js:11:19)
    at GlobalConfig.load (C:\Users\fcatae\AppData\Roaming\npm\node_modules\dxconfig\lib\globalconfig.js:11:26)
    at Object.<anonymous> (C:\Users\fcatae\AppData\Roaming\npm\node_modules\dxconfig\lib\main.js:31:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by fcatae** [comment]
fix the command line
